# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d1f12219624c2970a2d9d035685b7479ae2eb8261ea6f1df177e3561e6fa6bbaab5b783bcc9ffdc567ee622ffe96b8a26e5af1d9819f3b34a3da985242d14e8d

test:
  secret_key_base: f6315e07138affe0dbf72ca59420fe09c538085228ffaa9fc294733558f1046764b00e6bf36745e8f235a5e0fcb96ac9c1671dd200033aa583b1d843cd7945e3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
